export const DEV_CATEGORY_SELECTED = 'DEV_CATEGORY_SELECTED';
export const SELECT_VIDEO = 'SELECT_VIDEO';
export const SET_VIDEOS = 'SEARCH_VIDEOS';
export const IS_SEARCH = 'IS_SEARCH';
export const CURRENT_PAGE = 'CURRENT_PAGE';
